### ISSUE TITLE
enforce airbnb-base linting

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/design-website#9]
@rofe, i am not sure why this doesn;t seem to be setup in an action? or is it and just don't see it in the PR?

**Comment by rofe** [comment]
This seems to be related to PRs coming from forks... the tests are running on local branches as expected:
https://github.com/adobe/design-website/runs/3569202155?check_suite_focus=true

I did a bit of research, and it turns out that GH prohibits running workflows on the target repo/branch for security reasons if the code is originating from a fork. However a lot of people [complained about it](https://github.community/t/github-workflow-not-running-from-pull-request-from-forked-repository/16379) so GH eventually introduced a ["Run workflows from fork pull requests"](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/) option, but unfortunately it is only available for private repos.

For public repos, it seems like the `pull_request_target` event might be an option to run workflows in the fork, however there are [security concerns](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/) around potentially leaking secrets...

The best (albeit a bit more laborious) way I can think of is to merge PRs from forks into a non-main branch on the target repo, then opening another PR for that branch to run the workflows and fix any issues before merging to main.
