### ISSUE TITLE
"Cards" on Toolkit Landing & Inclusive Design pages have truncated descriptions

### ISSUE THREAD

**Issue by sharrocksb** [adobe/design-website#91]
Since these blocks link off the site, it's important that all of the content appears. We can edit words down, if I can understand the limitations on text.

The goal is to eliminate the 'ellipses' in the text section.

<img width="1552" alt="Screen Shot 2022-02-22 at 10 14 36 PM" src="https://user-images.githubusercontent.com/100241986/155269958-b7e802b4-1a8c-4274-b341-2b98295dcf08.png">

**Comment by pfulton** [comment]
I'm unsure why, but it looks like we're not getting the full text in the [description](https://github.com/adobe/design-website/blob/26cc5c3ff29eae3f577c159ee7147e03a9b4a353/blocks/cards/cards.js#L10). We'll need to investigate.

**Comment by davidnuescheler** [comment]
yeah, i think the issue is that the this is populated from `og:description` or similar... which has a size limit. i think we could consider indexing it different in `helix-query.yaml`, but i am not sure how much value there is, as `og:description` (or similar) will be used by most third party systems.

it may be that the description is only limited if it is taken from the actual content (which short of putting the entire body in the description, will have to truncate at some point), and placing a specific `Description` metadata property (for the cases where there is an issue) may address the issue.

**Comment by davidnuescheler** [comment]
seems to work... https://main--design-website--adobe.hlx3.page/toolkit/

**Comment by pfulton** [comment]
Awesome. Thanks @davidnuescheler - I think we're good here. This is working locally for me now.
